### ISSUE TITLE
view size is not compatible with input tensor's size

### ISSUE THREAD

**Issue by MyraBaba** [blacknwhite5/Activity-Preserving-Video-Face-Anonymization#3]
Hi @blacknwhite5 

I have below error 

`(ArcFace-Multiplex-Recognition) bc@bcl:~/Projects/Activity-Preserving-Video-Face-Anonymization/demo$ python3 demo_cam.py 
==> Face detector loaded
initialization method [normal]
==> loading the model from pretrained/model_1.pth
==> netG loaded
Traceback (most recent call last):
  File "demo_cam.py", line 136, in <module>
    demo(netF, netG)
  File "demo_cam.py", line 67, in demo
    box_info = detect(img, netF)
  File "demo_cam.py", line 27, in detect
    ssh_rois = netF(img_data, img_info)
  File "/home/bc/.venv/ArcFace-Multiplex-Recognition/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bc/Projects/Activity-Preserving-Video-Face-Anonymization/demo/SSH/model/SSH.py", line 159, in forward
    m3_ssh_cls_score_reshape = self.reshape(m3_ssh_cls_score, 2)
  File "/home/bc/Projects/Activity-Preserving-Video-Face-Anonymization/demo/SSH/model/SSH.py", line 51, in reshape
    input_shape[3]
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
`

**Comment by MyraBaba** [comment]
@blacknwhite5  @mryoo  is this a dead repo ?

**Comment by MyraBaba** [comment]
closed
